#spring.application.name=movieApp
#
#spring.datasource.url=jdbc:mysql://localhost:3306/movie
#spring.datasource.username=root
#spring.datasource.password=sarbajit
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#
#project.fileLocation=files/
#
#base.url=http://localhost:8080/

spring.application.name=movieApp

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/movie}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sarbajit}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.MySQL8Dialect}

server.port=${PORT:8080}

project.fileLocation=${PROJECT_FILELOCATION:files/}
base.url=${BASE_URL:http://localhost:8080/}
